# See https://github.com/dugalh/homonim/blob/main/docs/usage.rst#advanced-options for detailed documentation

# Correction configuration
param_image: False
mask_partial: False
threads: 0
max_block_mem: 100
proc_crs: auto

# Model configuration
downsampling: average
upsampling: cubic_spline
r2_inpaint_thresh: 0.25

# Format of output (corrected) image
driver: GTiff
dtype: float32
nodata: .nan

# Driver specific creation options
creation_options:
  tiled: True
  blockxsize: 512
  blockysize: 512
  compress: deflate
  interleave: band
  photometric:
